### PR TITLE
Mention golint in the README.md

### PR DESCRIPTION
**Pull request by Alehanz**
It was suggested over here
https://github.com/thoughtbot/hound/pull/926#discussion_r39630850 that
adding a mention of golint might be a good idea.

### CODE REVIEW

**Comment by tute** [comment]
:+1:

**Comment by bernerdschaefer** [comment]
Oops! I missed this.

@Alehanz Would you mind squashing the two commits and pushing again, so I can merge? Thanks!

**Comment by Alehanz** [comment]
@bernerdschaefer I've messed up and lost my original fork. So I've forked it again and added the same changes. Hope that's not too bad. I'll make the pull request now.

**Comment by bernerdschaefer** [comment]
Closing in favor of #9.

**Pull request closed without merging**
